title: Adam Pang
url: "https://adampang.com"
email: adam@adampang.com

exclude:
  - _private/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/

# Site settings
timezone: America/Los_Angeles
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

theme: minima

# Posts configuration
permalink: /:title/

# Collections
collections:
  jekyll_posts:
    output: true
    permalink: /:title/
  curations:
    output: false

# Defaults
defaults:
  - scope:
      path: "_jekyll_posts"
      type: "jekyll_posts"
    values:
      layout: "post"
